server:
  port: 8080

spring:
  application:
    name: api-gateway

  config:
    import: "optional:configserver:http://localhost:8888"

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false

          routes:
            - id: inventory-service-route
              uri: lb://inventory-service
              predicates:
                - Path=/api/equipment/**
              filters:
                - RewritePath=/api/equipment(?<segment>/?.*), /equipment${segment}

            - id: loan-service-route
              uri: lb://loan-service
              predicates:
                - Path=/api/loans/**
              filters:
                - RewritePath=/api/loans(?<segment>/?.*), /loans${segment}

jwt:
  secret: ${JWT_SECRET}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoint:
    gateway:
      access: unrestricted
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.loadbalancer: TRACE
    reactor.netty.http.client: DEBUG
    com.emergencylending.gateway: DEBUG